-- ============================================================
-- MEU-ENXOVAL — Schema COMPLETO (idempotente, rodar quantas vezes quiser)
-- ============================================================
-- COMO USAR:
--   1. Abra o painel do Supabase (https://supabase.com/dashboard)
--   2. Selecione o projeto: fgbzyalqtqkogjojcebw
--   3. Vá em SQL Editor > New query
--   4. Cole TODO este arquivo e clique em "Run"
--   5. Na primeira vez que o casal logar na área do casal,
--      cada um clica em "Tornar-me administrador" (máx. 2)
--
-- OBSERVAÇÃO: 100% idempotente — pode rodar de novo sem erro.
-- Corrige bancos antigos que só tinham couple_checklist e
-- couple_budget (cria as tabelas/funções/políticas que faltam).
-- ============================================================

-- ------------------------------------------------------------
-- 1. TABELA: itens do checklist (enxoval e casamento)
--    (create if not exists para bancos criados antes deste schema)
-- ------------------------------------------------------------
create table if not exists public.couple_checklist (
  id bigint generated by default as identity primary key,
  item_key text not null unique,
  item_id text not null,
  list_type text not null,
  category_id text not null,
  item_name text not null,
  checked boolean not null default false,
  is_custom boolean not null default false,
  deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists couple_checklist_list_type_idx
  on public.couple_checklist (list_type);

-- ------------------------------------------------------------
-- 2. TABELA: orçamento do casal
-- ------------------------------------------------------------
create table if not exists public.couple_budget (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'Outros',
  planned_value numeric not null default 0,
  actual_value numeric not null default 0,
  paid_value numeric not null default 0,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

-- ------------------------------------------------------------
-- 3. TABELA: e-mails dos administradores (o casal)
-- ------------------------------------------------------------
create table if not exists public.admin_emails (
  email text primary key,
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 4. TABELA: reservas de presentes feitas pelos convidados
--    item_key   = "enxoval:categoria:item" (mesma chave do checklist)
--    guest_name = nome digitado pelo convidado
--    Uma única reserva por item (unique).
-- ------------------------------------------------------------
create table if not exists public.gift_reservations (
  id bigint generated by default as identity primary key,
  item_key text not null unique,
  guest_name text not null,
  created_at timestamptz not null default now()
);

-- item_key já é UNIQUE: o índice adicional é redundante.

-- ------------------------------------------------------------
-- 5. FUNÇÃO: o usuário logado é administrador?
-- ------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_emails
    where email = auth.jwt() ->> 'email'
  );
$$;

-- ------------------------------------------------------------
-- 6. FUNÇÃO: primeiro acesso do casal (máx. 2 admins)
--    Cada membro do casal loga e clica em "Tornar-me admin".
--    Atômica: o lock serializa claims concorrentes, impedindo
--    que 2 requisições simultâneas criem um 3º admin.
-- ------------------------------------------------------------
create or replace function public.claim_admin()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := auth.jwt() ->> 'email';
begin
  if v_email is null then
    return false;
  end if;

  lock table public.admin_emails in exclusive mode;

  if exists (
    select 1 from public.admin_emails where email = v_email
  ) then
    return true;
  end if;

  if (select count(*) from public.admin_emails) >= 2 then
    return false;
  end if;

  insert into public.admin_emails (email) values (v_email);
  return true;
end;
$$;

-- ------------------------------------------------------------
-- 7. FUNÇÃO: reservar um presente (convidado)
--    Retorna true se reservou, false se já está reservado.
--    Atômica: on conflict impede reservas simultâneas
--    do mesmo item (2º pedido recebe false, não erro).
-- ------------------------------------------------------------
create or replace function public.reserve_gift(
  p_item_key text,
  p_guest_name text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_item_key is null or p_item_key = '' then
    return false;
  end if;

  p_guest_name := trim(p_guest_name);

  if p_guest_name is null or length(p_guest_name) < 2
     or length(p_guest_name) > 80 then
    return false;
  end if;

  insert into public.gift_reservations (item_key, guest_name)
  values (p_item_key, p_guest_name)
  on conflict (item_key) do nothing;

  return found;
end;
$$;

-- ------------------------------------------------------------
-- 8. FUNÇÃO: cancelar a própria reserva (convidado)
--    Só cancela se o nome bater com a reserva.
-- ------------------------------------------------------------
create or replace function public.cancel_gift(
  p_item_key text,
  p_guest_name text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.gift_reservations
  where item_key = p_item_key
    and lower(guest_name) = lower(trim(p_guest_name));

  return found;
end;
$$;

-- ------------------------------------------------------------
-- 9. FUNÇÃO: cancelar reserva como administrador
-- ------------------------------------------------------------
create or replace function public.cancel_gift_admin(
  p_item_key text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    return false;
  end if;

  delete from public.gift_reservations
  where item_key = p_item_key;

  return found;
end;
$$;

-- ------------------------------------------------------------
-- 10. GRANTS (quem pode chamar as funções)
-- ------------------------------------------------------------
grant execute on function public.is_admin() to authenticated;
grant execute on function public.claim_admin() to authenticated;
grant execute on function public.reserve_gift(text, text)
  to anon, authenticated;
grant execute on function public.cancel_gift(text, text)
  to anon, authenticated;
grant execute on function public.cancel_gift_admin(text)
  to authenticated;

-- ------------------------------------------------------------
-- 11. ROW LEVEL SECURITY
-- ------------------------------------------------------------
alter table public.admin_emails
  enable row level security;
alter table public.gift_reservations
  enable row level security;
alter table public.couple_checklist
  enable row level security;
alter table public.couple_budget
  enable row level security;

-- --------------------------------------
-- admin_emails: cada usuário só vê o próprio e-mail
-- --------------------------------------
drop policy if exists "admin_emails_select_self"
  on public.admin_emails;
create policy "admin_emails_select_self"
  on public.admin_emails
  for select to authenticated
  using (email = auth.jwt() ->> 'email');

-- --------------------------------------
-- gift_reservations: leitura pública (todos veem
-- quem reservou), escrita apenas via funções (RPC)
-- --------------------------------------
drop policy if exists "gift_reservations_select_public"
  on public.gift_reservations;
create policy "gift_reservations_select_public"
  on public.gift_reservations
  for select to anon, authenticated
  using (true);

-- --------------------------------------
-- couple_checklist: qualquer visitante PODE LER
-- (a lista de presentes é pública), mas só o casal
-- pode marcar/adicionar/remover itens
-- --------------------------------------
drop policy if exists "couple_checklist_select_public"
  on public.couple_checklist;
create policy "couple_checklist_select_public"
  on public.couple_checklist
  for select to anon, authenticated
  using (true);

drop policy if exists "couple_checklist_write_admin"
  on public.couple_checklist;
create policy "couple_checklist_write_admin"
  on public.couple_checklist
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- --------------------------------------
-- couple_budget: 100% privado — somente o casal
-- --------------------------------------
drop policy if exists "couple_budget_admin_all"
  on public.couple_budget;
create policy "couple_budget_admin_all"
  on public.couple_budget
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());
